version: "3"
services:
  mysql:
    image: "mysql:5"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  server:
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - MYSQL_DB=mysql
      - MYSQL_USER=root
    links:
      - mysql
      - redis